name: "ON-DEMAND: Automation UI"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branches"
        required: true
        default: master
        type: choice
        options:
          - master
          - develop
      command:
        description: "script"
        required: true
        default: "cy:run"
        type: choice
        options:
          - "cy:run"
          - "cy:run:chrome"
  branches: ${{ github.event.inputs.branch }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run ${{ github.event.inputs.command }}
